# Generated by Django 5.1.1 on 2024-09-18 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='Title',
            new_name='titulo',
        ),
    ]
