# Generated by Django 5.1.1 on 2024-09-19 22:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0002_rename_title_curso_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='criando_em',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
