# Generated by Django 5.1.1 on 2024-09-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0004_aulas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aulas',
            name='video',
            field=models.URLField(max_length=500),
        ),
    ]
