# Generated by Django 5.1.1 on 2024-09-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0007_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='image/'),
        ),
    ]
