# Generated by Django 5.1.1 on 2024-09-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginas', '0008_alter_perfil_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='image/'),
        ),
    ]
